version: '2.4'

services:
  mpi_head:
    build: .
    ports:
      - "2222:22"
    volumes:
      - ./compartido:/compartido
    depends_on:
      - mpi_node

  mpi_node:
    build: .
    volumes:
      - ./compartido:/compartido
